### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by fosskers** [adinapoli/haste-jquery#1]
...so that I can experiment with it in a cabal sandbox :)

**Comment by adinapoli** [comment]
Hi there! Glad you are keen to give this a go, but alas it's nothing more of an unfinished experiment and, as such, not of quality enough to be uploaded on Hackage. Don't despair though, as you don't need it to be on Hackage to play with it! Just clone the repo within the directory holding your project, and let cabal install it (example):

```
cd your_proj
cabal sandbox init
git clone  git@github.com:adinapoli/haste-jquery.git
cabal install haste-jquery/haste-jquery.cabal #Don't change directory, stay inside your_proj
```

And cabal will honour the sandbox and install the package there ;)
Alfredo

**Comment by fosskers** [comment]
Any desire to bring it to production level? I'm sure Haste could use it.

**Comment by adinapoli** [comment]
You are certainly welcome to do so! I can give you admin rights for the repo, and I will be happy to accept PR, if that helps ;)

**Comment by fosskers** [comment]
Let me learn more about Haste and how this library binds to JS before I make that jump.

**Comment by johncant** [comment]
Hi @fosskers, I suspect we might both be making some contributions to this repo over the next few days/weeks! Lets coordinate a bit. I'm also wondering whether we can get some stuff from fay-jquery (I implemented Fay bindings for jQuery Deferred)

**Comment by fosskers** [comment]
I won't have time for this for at least a month unfortunately.

**Comment by johncant** [comment]
No worries, I'll be sure to send lots of pull requests this way!

**Comment by adinapoli** [comment]
Please do, guys ;)

**Comment by fosskers** [comment]
Despite being an "experiment" it's what's endorsed as the official jQuery wrapper. For Haste to be competitive we need this up to snuff, as everybody and their grandmothers use jQuery.
